version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/appdb
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
volumes:
  postgres-data:
